fix #11 #12
HDCodePractice/EnglishHelper pull request #77
Opened 2021-12-13 04:10 UTC by lben1216

2021-12-16 01:44 UTC, hdcola requested changes

2021-12-16 01:44 UTC, hdcola commented on dict/user_chapter_dict.py
> +
哈哈，这是一个module，但是叫dict似乎不太对 :)

2021-12-16 01:44 UTC, hdcola commented on dict/user_chapter_dict.py
> +    stored_data=fetch_user_data(uid)
如果不做global，这个能改变外面的stored_data吗？

2021-12-16 01:44 UTC, hdcola commented on dict/user_chapter_dict.py
> +    if stored_data == None: #如果stored_data是空的，就根据chapter_dict重新生成stored_data
如果chapter_dict变化了呢？

2021-12-16 01:44 UTC, hdcola commented on dict/user_chapter_dict.py
> +            stored_data[uid][key] = []
如果是第一次使用会报错
  File "/Users/hd/work/EnglishHelper/utils/filters.py", line 41, in decorator_check_chatid_permission
    func(*args, **kwargs)
  File "/Users/hd/work/EnglishHelper/cmdproc/customize_cmd.py", line 81, in custom_chapter_command
    gen_user_chapter_dict(str(user_id))
  File "/Users/hd/work/EnglishHelper/dict/user_chapter_dict.py", line 11, in gen_user_chapter_dict
    stored_data[uid][key] = []

2021-12-16 01:44 UTC, hdcola commented on cmdproc/preview_cmd.py
> +    return topic_preview_msg,topic_menu_keyboard
跪求 unit test

2021-12-16 01:50 UTC, hdcola requested changes

2021-12-16 01:50 UTC, hdcola commented on dict/user_chapter_dict.py
> +        user_chapter_dict = read_file_to_dict("user_chapter_dict.json")
应该存到 config.ENV.DATA_DIR 里去，这个文件不是发行软件的一部分，所以不能放在当前目录，否则在用户更新软件版本时就会消失的

2022-01-02 18:58 UTC, lben1216 commented on utils/filters.py
> +def check_callback_user(uid,data):
房东哥我有点不太明白这个， 您是说把变量命名成filter吗？

2022-01-02 19:12 UTC, lben1216 commented on dict/user_chapter_dict.py
> +    stored_data=fetch_user_data(uid)
我做了测试，应该是可以直接改变stored_data的数据

2022-01-02 19:14 UTC, lben1216 commented on dict/user_chapter_dict.py
> +            stored_data[uid][key] = []
添加了一个检查文件是否存在的功能

2022-01-02 19:19 UTC, lben1216 commented on dict/user_chapter_dict.py
> +        user_chapter_dict = read_file_to_dict("user_chapter_dict.json")
将user_chapter_dict.json存进了 ENV.DARA_DIR里

2022-01-02 22:49 UTC, lben1216 commented on dict/user_chapter_dict.py
> +    if stored_data == None: #如果stored_data是空的，就根据chapter_dict重新生成stored_data
添加了一个同步chapter_dict的功能

2022-01-03 01:49 UTC, hdcola commented on utils/filters.py
> +def check_callback_user(uid,data):
哈哈，这种函数适合写成filter，在python中有一个语法糖可以使用 @ 放在一个函数前做filter。

可以参考这个实现
https://github.com/HDCodePractice/EnglishHelper/blob/fb90cfe87be53884c727f5a87362496bd47f053b/utils/filters.py#L4

这样使用
https://github.com/HDCodePractice/EnglishHelper/blob/fb90cfe87be53884c727f5a87362496bd47f053b/cmdproc/upload.py#L39

2022-01-09 04:08 UTC, lben1216 commented on utils/filters.py
> +def check_callback_user(uid,data):
原来是这样，我大概明白了。 我试着把这个check_user改成filter， 但是发现不太适合，因为这个function是在用户点完之后才会触发， 如果用filter的话似乎没啥用啊， 不知道我这么想对不对。

2022-05-04 20:36 UTC, closed without merging